// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	model "order-service-wbtech/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// Cache is an autogenerated mock type for the Cache type
type Cache struct {
	mock.Mock
}

// Get provides a mock function with given fields: orderUID
func (_m *Cache) Get(orderUID string) (*model.Order, bool) {
	ret := _m.Called(orderUID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.Order
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (*model.Order, bool)); ok {
		return rf(orderUID)
	}
	if rf, ok := ret.Get(0).(func(string) *model.Order); ok {
		r0 = rf(orderUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(orderUID)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// Set provides a mock function with given fields: order
func (_m *Cache) Set(order *model.Order) {
	_m.Called(order)
}

// NewCache creates a new instance of Cache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *Cache {
	mock := &Cache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
